name: Sync Main Branch with VGX

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Push to other repository
        run: |
          git remote add outro_origin https://github.com/DeveloperQC/vgx-admin-frontend.git
          git push outro_origin main
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
